#:import FadeTransition  kivy.uix.screenmanager.FadeTransition
<StyleSearchScreen@MDTextField>:
    hint_text: "default: 0"
    helper_text_mode: "on_focus"
    helper_text:""

<StyleBackGround@BoxLayout>:
    orientation: "vertical"
    MDToolbar:
        id: toolbar
        title: app.title
        md_bg_color: app.theme_cls.primary_color
        background_palette: "Primary"
        left_action_items: [["menu", lambda x: None]]

    MDSeparator:

<Row@BoxLayout>:
    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Rectangle:
            size: self.size
            pos: self.pos
    value: ''
    BoxLayout:
        orientation:'horizontal'
        Button:
            size_hint_x: 0.8
            text: root.value
            on_press: root.btn_event(root.index, True)

        Button:
            size_hint_x: 0.2
            text: "UniProt"
            on_press: root.btn_event(root.index, False)

<SSTextBoxLayout@BoxLayout>:
    orientation:'horizontal'
    size:self.size
    size_hint_x: 0.7


<SSLabel@Label>:
    font_size: 32
    text_size: self.size             # ラベルサイズを設定.これによりhalign, valignが変更可能になる
    halign: 'left'                   # 横方向(左揃え)

<ScreenSearch>:
    StyleBackGround:

        MDSeparator:
        ScrollView:
            BoxLayout:
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                padding: dp(48)
                spacing: 10

                MDLabel:
                    text: "Threshold value"

                StyleSearchScreen:
                    id:th_val
                    helper_text:"Please input number between 0 < x < 1.0"


                MDLabel:
                    text: "Threshold length"

                StyleSearchScreen:
                    id:th_len
                    helper_text:"Please input number between 0 < x"


                MDLabel:
                    text: "Fill gap"

                StyleSearchScreen:
                    id:fill_gap
                    helper_text:"Please input number between 0 < x"


                MDRaisedButton:
                    text: "Search with this conditions"
                    pos_hint: {"center_x": .5}
                    on_press:
                        root.btn_event()

<ScreenWait>:
    StyleBackGround:

        Label:
            size_hint_y: 0.1
            text:''

        Label:
            text_size: self.size
            text:'Searching Now'
            valign:'bottom'
            halign:'left'
            size_hint_x: 0.5
            size_hint_y:0.4
            font_size: 24
            pos_hint: {"x":0, "y":0.9}

        Image:
            size: root.size
            allow_stretch: True
            keep_ratio: False
            size_hint_x:1
            size_hint_y:0.4
            source:'loading4.gif'


        Label:
            size_hint_y: 0.1
            text:''

        MDRaisedButton:
            text: "Search with this conditions"
            pos_hint: {"center_x": .5}
            on_press: root.btn_event()

<ScreenOut>:
    rv: rv
    StyleBackGround:
        RecycleView:
            id: rv
            scroll_type: ['bars', 'content']
            scroll_wheel_distance: dp(114)
            bar_width: dp(10)
            RecycleBoxLayout:
                viewclass: 'Row'
                default_size: None, dp(56)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height
                orientation: 'vertical'
                spacing: dp(2)







