#:import FadeTransition  kivy.uix.screenmanager.FadeTransition
<Row@BoxLayout>:
    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Rectangle:
            size: self.size
            pos: self.pos
    value: ''
    Button:
        text: root.value

<value_select@Label>:
    text_size: self.size
    size_hint_x: 0.25
    size_hint_y:0.35
    font_size: 24
    text:'0'

<ImageButton@Button>:
    source: None
    background_color:1, 1, 1, 0.7
    text:"Search"
    Image:
        source: root.source
        pos: root.pos
        size: root.size

<TopScreen>:
    FloatLayout:
        size:root.size
        canvas.before:
            Color:
                rgba: 0.4, 0.4, 0.4, 0.6
            Rectangle:
                size: self.size

        Image:
            source: 'body_cell.png'
            size:root.size
            size_hint:None,None
        Label:
            text_size: self.size
            text:'MobiDB'
            halign: 'center'
            size_hint_x: 1
            size_hint_y:0.5
            font_size: 24
            pos_hint: {"x":0, "y":0.45}

<SearchScreen>:
    BoxLayout:
        orientation:'vertical'
        size:root.size
        canvas.before:
            Color:
                rgba: 0.4, 0.4, 0.4, 0.6
            Rectangle:
                size: self.size
                #pos: self.pos
        Label:
            text_size: self.size
            text:'Searching in MobiDB'

            halign: 'left'
            size_hint_x: 1
            size_hint_y:0.5
            font_size: 24

        Label:
            size_hint_y: 0.1
            text:''

        BoxLayout:
            size_hint_x:0.83
            size_hint_y:0.38
            orientation:'horizontal'
            pos_hint: {"x":0.158, "y":0.84}

            TextInput:
                id:text_box
                font_size: 22
                hint_text:'keyword'
                focus: True
                on_text_validate: root.btnClicked_text()

        Label:
            size_hint_y: 0.1
            text:''

        FloatLayout:
            Image:
                source: 'logo-from-tunnel.png'
                size_hint_x: 0.154
                size_hint_y:0.44
                pos_hint: {"x":0, "y":1.07}

            BoxLayout:
                size_hint_x:0.5
                size_hint_y:0.35
                orientation:'horizontal'
                pos_hint: {"x":0.22, "y":0.7}

                TextInput:
                    id:text_box_score
                    font_size: 22
                    hint_text:'score'
                    focus: True
                    on_text_validate: root.search_to_uniprot_thread()

            value_select:
                text:'Score'
                pos_hint: {"x":0.03, "y":0.76}

            BoxLayout:
                size_hint_x:0.5
                size_hint_y:0.35
                orientation:'horizontal'
                pos_hint: {"x":0.22, "y":0.35}

                TextInput:
                    id:text_box_lengs
                    font_size: 22
                    hint_text:'lengs'
                    focus: True
                    on_text_validate: root.search_to_uniprot_thread()

            value_select:
                text:'Lengs'
                pos_hint: {"x":0.03, "y":0.4}

            BoxLayout:
                size_hint_x:0.5
                size_hint_y:0.35
                orientation:'horizontal'
                pos_hint: {"x":0.22, "y":0}

                TextInput:
                    id:text_box_gap
                    font_size: 22
                    hint_text:'Gap'
                    focus: True
                    on_text_validate: root.search_to_uniprot_thread()

            value_select:
                text:'Gap'
                pos_hint: {"x":0.03, "y":0}

            ImageButton:
                source: 'search_icon_L.png'
                size_hint_x: 0.2
                size_hint_y: 0.85
                pos_hint: {"x":0.8, "y":0}
                on_press:
                    root.press_btn()

<WaitScreen>:
    BoxLayout:
        orientation:'vertical'
        size: root.size
        canvas.before:
            Color:
                rgba: 0.4, 0.4, 0.4, 0.6
            Rectangle:
                size: self.size

        Label:
            size_hint_y: 0.1
            text:''

        Label:
            text_size: self.size
            text:'Search Now'
            valign:'top'
            halign:'left'
            size_hint_x: 0.5
            size_hint_y:0.4
            font_size: 24
            pos_hint: {"x":0, "y":1}

        Image:
            source:root.source
            size: root.size
            allow_stretch: True
            keep_ratio: False
            size_hint_x:1
            size_hint_y:0.4

        Label:
            size_hint_y: 0.1
            text:''

        Button:
            size: 50,50
            size_hint: None,None
            text:"cancel"
            on_press: root.press_btn()#Wait_Screenのメソッドが実行される

<OutputScreen>:
    rv: rv
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            canvas:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
            orientation: 'vertical'
            GridLayout:
                cols: 3
                rows: 1
                size_hint_y: None
                height: dp(54)
                padding: dp(8)
                spacing: dp(4)
                BoxLayout:
                    spacing: dp(8)
                    Button:
                        text: 'Sort'
                        on_press: root.sort(sort_list.text)
                    TextInput:
                        id: sort_list
                        size_hint_x: 1
                        hint_text: 'select method'
                        padding: dp(10), dp(10), 0, 0
                BoxLayout:
                    spacing: dp(8)
                    Button:
                        text: 'Filter'
                        on_press: root.filter(filter_list.text)
                    TextInput:
                        id: filter_list
                        size_hint_x: 1
                        hint_text: 'select method'
                        padding: dp(10), dp(10), 0, 0
                Button:
                    text: 'return window'
                    on_press: root.return_window()

            RecycleView:
                id: rv
                scroll_type: ['bars', 'content']
                scroll_wheel_distance: dp(114)
                bar_width: dp(10)
                RecycleBoxLayout:
                    viewclass: 'Row'
                    default_size: None, dp(56)
                    default_size_hint: 1, None
                    size_hint_y: None
                    height: self.minimum_height
                    orientation: 'vertical'
                    spacing: dp(2)







